///Security HASH, SHA256
enum EmvGuiType {
  ///CO.COM.ACH.RED - ACH
  ACH,

  ///CO.COM.BRC.RED - BANCO DE LA REPUBLICA
  BRC,

  ///CO.COM.CRB.SEC - CREDIBANCO
  CRB,

  ///CO.COM.MCCA.SEC - MASTERCARD
  MCCA,
  
  ///CO.COM.RBM.SEC - REDEBAN
  RBM,

  ///CO.COM.SVB.LLA - SERVIBANCA
  SVB,

  ///CO.COM.VCSS.LLA - VISA
  VCSS,

  ///CO.COM.VISI.LLA - VISIONAMOS
  VISI,

  ///CO.COM.RED.TRXID - REDES INTERBANCARIAS  
  RED,
  ///EMPTY DATA
  empty,
}